/* Single source of truth for eFixMate team profile pages.
   Add a new member by appending an object here, then run:
     node landing/scripts/build-team.mjs
   That regenerates landing/team/<slug>/index.html for every active member.
   Do not add facts here (bio, achievements, dates) that aren't already
   verified/public — see the "Rules" note in build-team.mjs. */

export const ORG = {
  name: 'eFixMate',
  url: 'https://efixmate.com',
  logo: 'https://efixmate.com/assets/efixmate-logo.webp',
};

export const team = [
  {
    slug: 'aman-kumar',
    name: 'Aman Kumar',
    designation: 'CEO & Director',
    category: 'Founders & Directors',
    department: 'Executive Leadership',
    focusStat: 'Strategy & Growth',
    orgPath: ['Leadership', 'Founders & Directors', 'CEO & Director'],
    photo: '/assets/team/aman.jpeg',
    initials: 'AK',
    tagline: 'Building the vision, strategy and growth behind eFixMate.',
    bio: "Aman Kumar is the CEO & Director at eFixMate. He leads business strategy and company vision, and is responsible for the company's overall growth, partnerships and leadership direction.",
    responsibilities: ['Business Strategy', 'Company Vision', 'Growth', 'Partnerships', 'Leadership'],
    focusAreas: ['Business Strategy', 'Company Vision', 'Growth', 'Partnerships', 'Leadership'],
    journey: [],
    socialLinks: {},
    order: 1,
    active: true,
    seo: {
      title: 'Aman Kumar – CEO & Director | eFixMate',
      description: 'Meet Aman Kumar, CEO & Director at eFixMate, and his role in business strategy, company vision, growth, partnerships and overall leadership.',
    },
  },
  {
    slug: 'radheshyam-sahu',
    name: 'Radheshyam Sahu',
    designation: 'COO & Director',
    category: 'Founders & Directors',
    department: 'Executive Leadership',
    focusStat: 'Operations & Delivery',
    orgPath: ['Leadership', 'Founders & Directors', 'COO & Director'],
    photo: '/assets/team/radhe.jpeg',
    initials: 'RS',
    tagline: 'Running the operations, technician network and service delivery behind eFixMate.',
    bio: 'Radheshyam Sahu is the COO & Director at eFixMate. He oversees day-to-day operations, service delivery and the technician network, along with administration.',
    responsibilities: ['Operations', 'Service Delivery', 'Technician Network', 'Administration'],
    focusAreas: ['Operations', 'Service Delivery', 'Technician Network', 'Administration'],
    journey: [],
    socialLinks: {},
    order: 2,
    active: true,
    seo: {
      title: 'Radheshyam Sahu – COO & Director | eFixMate',
      description: 'Meet Radheshyam Sahu, COO & Director at eFixMate, and his role in operations, service delivery, the technician network and administration.',
    },
  },
  {
    slug: 'karan',
    name: 'Karan',
    designation: 'CTPO & Director',
    category: 'Founders & Directors',
    department: 'Executive Leadership',
    focusStat: 'Technology & Product',
    orgPath: ['Leadership', 'Founders & Directors', 'CTPO & Director'],
    photo: '/assets/team/karan.jpeg',
    initials: 'K',
    tagline: 'Building the technology and product behind eFixMate.',
    bio: "Karan is the CTPO & Director at eFixMate. He leads technology and product development, including engineering and the company's digital infrastructure.",
    responsibilities: ['Technology', 'Product Development', 'Engineering', 'Digital Infrastructure'],
    focusAreas: ['Technology', 'Product Development', 'Engineering', 'Digital Infrastructure'],
    journey: [],
    socialLinks: {},
    order: 3,
    active: true,
    seo: {
      title: 'Karan – CTPO & Director | eFixMate',
      description: 'Meet Karan, CTPO & Director at eFixMate, and his role in technology, product development, engineering and digital infrastructure.',
    },
  },
  {
    slug: 'rajkumar-sahu',
    name: 'Rajkumar Sahu',
    designation: 'Marketing Head (HOM)',
    category: 'Department Heads',
    department: 'Marketing',
    focusStat: 'Brand & Growth',
    orgPath: ['Leadership', 'Department Heads', 'Marketing'],
    photo: '/assets/team/rajkumar.jpeg',
    initials: 'RS',
    tagline: 'Driving the marketing, branding and growth behind eFixMate.',
    bio: 'Rajkumar Sahu is the Marketing Head (HOM) at eFixMate. He leads marketing and branding, and is responsible for customer acquisition, campaigns and partnerships.',
    responsibilities: ['Marketing', 'Branding', 'Customer Acquisition', 'Campaigns', 'Partnerships'],
    focusAreas: ['Marketing', 'Branding', 'Customer Acquisition', 'Campaigns', 'Partnerships'],
    journey: [],
    socialLinks: {},
    order: 4,
    active: true,
    seo: {
      title: 'Rajkumar Sahu – Marketing Head | eFixMate',
      description: 'Meet Rajkumar Sahu, Marketing Head (HOM) at eFixMate, and his role in marketing, branding, customer acquisition, campaigns and partnerships.',
    },
  },
  {
    slug: 'dinesh',
    name: 'Dinesh',
    designation: 'Finance Head (HOF)',
    category: 'Department Heads',
    department: 'Finance',
    focusStat: 'Accounting & Controls',
    orgPath: ['Leadership', 'Department Heads', 'Finance'],
    photo: '/assets/team/dinesh.jpeg',
    initials: 'D',
    tagline: 'Managing the finances and financial controls behind eFixMate.',
    bio: 'Dinesh is the Finance Head (HOF) at eFixMate. He oversees finance, accounting and budgeting, along with financial controls and reporting.',
    responsibilities: ['Finance', 'Accounting', 'Budgeting', 'Financial Controls', 'Reporting'],
    focusAreas: ['Finance', 'Accounting', 'Budgeting', 'Financial Controls', 'Reporting'],
    journey: [],
    socialLinks: {},
    order: 5,
    active: true,
    seo: {
      title: 'Dinesh – Finance Head | eFixMate',
      description: 'Meet Dinesh, Finance Head (HOF) at eFixMate, and his role in finance, accounting, budgeting, financial controls and reporting.',
    },
  },
  {
    slug: 'rajababu-banjare',
    name: 'Rajababu Banjare',
    designation: 'Operations Manager',
    category: 'Department Heads',
    department: 'Operations',
    focusStat: 'Scheduling & Quality',
    orgPath: ['Leadership', 'Department Heads', 'Operations'],
    photo: '/assets/team/raja-babu.jpeg',
    initials: 'RB',
    tagline: 'Keeping day-to-day operations and service quality running at eFixMate.',
    bio: 'Rajababu Banjare is the Operations Manager at eFixMate. He manages day-to-day operations, technician scheduling and service quality on the ground.',
    responsibilities: ['Day-to-day Operations', 'Technician Scheduling', 'Service Quality'],
    focusAreas: ['Day-to-day Operations', 'Technician Scheduling', 'Service Quality'],
    journey: [],
    socialLinks: {},
    order: 6,
    active: true,
    seo: {
      title: 'Rajababu Banjare – Operations Manager | eFixMate',
      description: 'Meet Rajababu Banjare, Operations Manager at eFixMate, and his role in day-to-day operations, technician scheduling and service quality.',
    },
  },
];

export const activeTeam = team.filter(m => m.active).sort((a, b) => a.order - b.order);
export const bySlug = Object.fromEntries(team.map(m => [m.slug, m]));
